name: 'Web Build and Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18'
      - name: Installing Yarn
        run: |
          sudo apt update
          sudo apt install yarn
          yarn --version
      - name: Install and Build
        working-directory: .
        run: |
          # yarn global add @vue/cli
          # yarn global add @vue/cli-service
          # yarn run build
          npm install --force
          npm run build
          cd dist
          cp index.html 404.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          DEPLOY_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
